- hosts: nodes
  become: yes
  tasks:
    - name: install public keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
